### Imports

In [2]:
import pandas as pd
import numpy as np
import os
import shutil

In [ ]:
df=pd.read_csv("LibriSpeechTrain/SPEAKERS_MODIFIED.txt",sep="|")

In [ ]:
df.info()

In [ ]:
df.columns

In [ ]:
#Stripping spaces from the columns name
df.columns=[i.strip() for i in df.columns]
df.columns

In [ ]:
#Striping spaces from the data values except columns that caontain int and float values
for i in df.columns[1:3]:
    df[i]=df[i].apply(lambda x:x.strip())
for i in df.columns[4:]:
    df[i]=df[i].apply(lambda x:x.strip())

In [ ]:
df['SUBSET'].value_counts().axes[0][2]

In [ ]:
df=df[df['SUBSET']=="train-clean-100"]

In [ ]:
df.shape

In [ ]:
df.head()

In [ ]:
df.drop(["SUBSET","MINUTES","NAME"],inplace=True,axis=1)

In [ ]:
df.reset_index(drop=True)

In [ ]:
file_path="LibriSpeechTrain/train-clean-100"

In [ ]:
#Making subdirectories
os.mkdir("male")
os.mkdir("female")

In [ ]:
def make_folders(files):
    
    z=0
    if files.SEX=="M":
        z=1
    print(files.ID,files.SEX,z)
    
    # Sets the name to be the path to where the file is in my computer
    file_name = os.path.join(os.path.abspath("LibriSpeechTrain/train-clean-100"+'/'+str(files.ID)))
    dir_list=os.listdir(file_name)
    if z==1:
        for i in dir_list:
            for j in os.listdir(file_name+"/"+i):
                #shutil.copy(src,dest)
                shutil.copy(file_name+"/"+i+"/"+j,"male/")
    else:
        for i in dir_list:
            for j in os.listdir(file_name+"/"+i):
                #shutil.copy(src,dest)
                shutil.copy(file_name+"/"+i+"/"+j,"female/")

In [131]:
df.apply(make_folders,axis=1)

19 F 0
26 M 1
27 M 1
32 F 0
39 F 0
40 F 0
60 M 1
78 M 1
83 F 0
87 F 0
89 F 0
103 F 0
118 M 1
125 F 0
150 F 0
163 M 1
196 M 1
198 F 0
200 F 0
201 M 1
211 F 0
226 F 0
229 M 1
233 M 1
248 F 0
250 F 0
254 M 1
289 F 0
298 F 0
302 F 0
307 M 1
311 M 1
322 F 0
328 F 0
332 M 1
374 M 1
403 F 0
405 M 1
412 M 1
426 F 0
441 F 0
445 M 1
446 M 1
458 M 1
460 M 1
481 M 1
587 F 0
625 M 1
669 F 0
696 F 0
730 F 0
831 M 1
839 M 1
887 F 0
909 M 1
911 M 1
1034 M 1
1040 M 1
1069 F 0
1081 M 1
1088 F 0
1098 F 0
1116 F 0
1183 F 0
1235 M 1
1246 F 0
1263 F 0
1334 M 1
1355 M 1
1363 F 0
1447 F 0
1455 M 1
1502 F 0
1553 F 0
1578 F 0
1594 M 1
1624 M 1
1723 M 1
1737 F 0
1743 M 1
1841 F 0
1867 M 1
1898 F 0
1926 F 0
1963 F 0
1970 F 0
1992 F 0
2002 M 1
2007 F 0
2092 F 0
2136 M 1
2159 M 1
2182 F 0
2196 F 0
2289 M 1
2384 M 1
2391 F 0
2416 F 0
2436 M 1
2514 M 1
2518 M 1
2691 F 0
2764 F 0
2817 F 0
2836 F 0
2843 M 1
2893 M 1
2910 F 0
2911 M 1
2952 M 1
2989 F 0
3112 F 0
3168 M 1
3214 M 1
3235 F 0
3240 M 1
3242 M 1
3259 F 0
3374 M 1
3436 M 1
3440 F 0
3486 M 1
3526 F 0
3607 M 1
3664 M 1
3699 M 1
3723 M 1
3807 M 1
3830 M 1
3857 M 1
3879 F 0
3947 F 0
3982 F 0
3983 F 0
4014 M 1
4018 M 1
4051 F 0
4088 F 0
4137 F 0
4160 F 0
4195 F 0
4214 F 0
4267 M 1
4297 F 0
4340 F 0
4362 F 0
4397 M 1
4406 M 1
4441 M 1
4481 F 0
4640 F 0
4680 F 0
4788 M 1
4813 M 1
4830 M 1
4853 F 0
4859 M 1
4898 M 1
5022 F 0
5049 M 1
5104 M 1
5163 F 0
5192 M 1
5322 M 1
5339 F 0
5390 M 1
5393 F 0
5456 M 1
5463 M 1
5514 F 0
5561 F 0
5652 F 0
5678 M 1
5688 F 0
5703 M 1
5750 M 1
5778 F 0
5789 F 0
5808 M 1
5867 F 0
6000 F 0
6019 M 1
6064 F 0
6078 F 0
6081 M 1
6147 F 0
6181 M 1
6209 M 1
6272 F 0
6367 M 1
6385 F 0
6415 F 0
6437 M 1
6454 M 1
6476 F 0
6529 M 1
6531 F 0
6563 M 1
6818 F 0
6836 M 1
6848 M 1
6880 M 1
6925 M 1
7059 F 0
7067 M 1
7078 F 0
7113 F 0
7148 F 0
7178 F 0
7190 M 1
7226 M 1
7264 M 1
7278 M 1
7302 F 0
7312 M 1
7367 M 1
7402 M 1
7447 M 1
7505 M 1
7511 F 0
7517 F 0
7635 F 0
7780 F 0
7794 F 0
7800 F 0
7859 F 0
8014 F 0
8051 F 0
8063 M 1
8088 M 1
8095 M 1
8098 M 1
8108 M 1
8123 F 0
8226 M 1
8238 F 0
8312 F 0
8324 F 0
8419 M 1
8425 M 1
8465 F 0
8468 F 0
8580 M 1
8609 M 1
8629 M 1
8630 M 1
8747 M 1
8770 M 1
8797 M 1
8838 M 1
8975 F 0

3       None
8       None
9       None
14      None
18      None
        ...
2451    None
2455    None
2462    None
2469    None
2479    None
Length: 251, dtype: object

In [7]:
#Removinf unnecessary text files from male and female directory
for i in os.listdir('male/'):
    if i[-3:]=='txt':
        os.remove("male/"+i)
        print(i)
for i in os.listdir('female/'):
    if i[-3:]=='txt':
        os.remove("female/"+i)
        print(i)

103-1240.trans.txt
103-1241.trans.txt
1069-133699.trans.txt
1069-133709.trans.txt
1088-129236.trans.txt
1088-134315.trans.txt
1088-134318.trans.txt
1098-133695.trans.txt
1116-132847.trans.txt
1116-132851.trans.txt
1116-137572.trans.txt
1183-124566.trans.txt
1183-128659.trans.txt
1183-133255.trans.txt
1183-133256.trans.txt
1246-124548.trans.txt
1246-124550.trans.txt
1246-135815.trans.txt
125-121124.trans.txt
125-121342.trans.txt
1263-138246.trans.txt
1263-139804.trans.txt
1263-141777.trans.txt
1363-135842.trans.txt
1363-139304.trans.txt
1447-130550.trans.txt
1447-130551.trans.txt
1447-130552.trans.txt
1447-17506.trans.txt
150-126107.trans.txt
150-126112.trans.txt
150-132655.trans.txt
1502-122615.trans.txt
1502-122619.trans.txt
1553-140047.trans.txt
1553-140048.trans.txt
1578-140045.trans.txt
1578-140049.trans.txt
1578-6379.trans.txt
1737-142396.trans.txt
1737-142397.trans.txt
1737-146161.trans.txt
1737-148989.trans.txt
1841-150351.trans.txt
1841-159771.trans.txt
1841-179183.trans.txt
1898-145702.trans.txt
1898-145715.trans.txt
1898-145720.trans.txt
1898-145724.trans.txt
19-198.trans.txt
19-227.trans.txt
1926-143879.trans.txt
1926-147979.trans.txt
1926-147987.trans.txt
1963-142393.trans.txt
1963-142776.trans.txt
1963-147036.trans.txt
1970-10594.trans.txt
1970-26100.trans.txt
1970-28415.trans.txt
198-126831.trans.txt
198-129977.trans.txt
198-209.trans.txt
1992-141719.trans.txt
200-124139.trans.txt
200-124140.trans.txt
200-126784.trans.txt
2007-132570.trans.txt
2007-149877.trans.txt
2092-145706.trans.txt
2092-145709.trans.txt
211-122425.trans.txt
211-122442.trans.txt
2182-150130.trans.txt
2182-181173.trans.txt
2182-181183.trans.txt
2196-170151.trans.txt
2196-170379.trans.txt
2196-174172.trans.txt
226-122538.trans.txt
226-131532.trans.txt
226-131533.trans.txt
2391-145015.trans.txt
2416-152137.trans.txt
2416-152139.trans.txt
248-130644.trans.txt
248-130652.trans.txt
248-130697.trans.txt
250-140277.trans.txt
250-142276.trans.txt
250-142286.trans.txt
2691-156745.trans.txt
2691-156750.trans.txt
2691-156755.trans.txt
2764-36616.trans.txt
2764-36617.trans.txt
2764-36619.trans.txt
2817-142371.trans.txt
2817-142380.trans.txt
2836-5354.trans.txt
2836-5355.trans.txt
289-121652.trans.txt
289-121665.trans.txt
2910-131096.trans.txt
298-126790.trans.txt
298-126791.trans.txt
2989-138028.trans.txt
2989-138035.trans.txt
302-123504.trans.txt
302-123516.trans.txt
302-123523.trans.txt
3112-9554.trans.txt
3112-9555.trans.txt
32-21625.trans.txt
32-21631.trans.txt
32-21634.trans.txt
32-4137.trans.txt
322-124146.trans.txt
322-124147.trans.txt
3235-11599.trans.txt
3235-28433.trans.txt
3235-28452.trans.txt
3259-158083.trans.txt
328-129766.trans.txt
3440-171006.trans.txt
3440-171009.trans.txt
3526-175658.trans.txt
3526-176651.trans.txt
3526-176653.trans.txt
3879-173592.trans.txt
3879-174923.trans.txt
39-121914.trans.txt
39-121915.trans.txt
39-121916.trans.txt
3947-13260.trans.txt
3947-13262.trans.txt
3982-178459.trans.txt
3982-182255.trans.txt
3983-5331.trans.txt
3983-5371.trans.txt
40-121026.trans.txt
40-222.trans.txt
403-126855.trans.txt
403-128339.trans.txt
403-216.trans.txt
4051-10927.trans.txt
4051-11217.trans.txt
4051-11218.trans.txt
4088-158077.trans.txt
4088-158079.trans.txt
4137-11701.trans.txt
4137-11702.trans.txt
4160-11549.trans.txt
4160-11550.trans.txt
4160-14187.trans.txt
4195-17507.trans.txt
4195-186236.trans.txt
4195-186237.trans.txt
4195-186238.trans.txt
4214-7146.trans.txt
426-122819.trans.txt
426-122821.trans.txt
426-122822.trans.txt
4297-13006.trans.txt
4297-13009.trans.txt
4340-15220.trans.txt
4362-15663.trans.txt
441-128982.trans.txt
441-128988.trans.txt
441-130108.trans.txt
4481-17498.trans.txt
4481-17499.trans.txt
4640-19187.trans.txt
4640-19188.trans.txt
4640-19189.trans.txt
4680-16026.trans.txt
4680-16041.trans.txt
4680-16042.trans.txt
4853-27670.trans.txt
4853-27671.trans.txt
4853-29413.trans.txt
5022-29405.trans.txt
5022-29411.trans.txt
5163-18515.trans.txt
5163-39921.trans.txt
5339-14133.trans.txt
5339-14134.trans.txt
5393-19218.trans.txt
5393-19219.trans.txt
5514-19192.trans.txt
5514-19193.trans.txt
5561-39621.trans.txt
5561-41615.trans.txt
5561-41616.trans.txt
5652-19215.trans.txt
5652-39938.trans.txt
5688-15787.trans.txt
5688-41232.trans.txt
5778-12761.trans.txt
5778-54535.trans.txt
5789-57158.trans.txt
5789-57195.trans.txt
5789-70653.trans.txt
5867-48852.trans.txt
587-41611.trans.txt
587-41619.trans.txt
587-54108.trans.txt
6000-55211.trans.txt
6000-86686.trans.txt
6064-300880.trans.txt
6064-56165.trans.txt
6064-56168.trans.txt
6078-54007.trans.txt
6078-54013.trans.txt
6147-34605.trans.txt
6147-34606.trans.txt
6147-34607.trans.txt
6272-70168.trans.txt
6272-70171.trans.txt
6272-70191.trans.txt
6385-220959.trans.txt
6385-34655.trans.txt
6385-34669.trans.txt
6415-100596.trans.txt
6415-111615.trans.txt
6415-116629.trans.txt
6476-57446.trans.txt
6476-96661.trans.txt
6531-61334.trans.txt
669-129061.trans.txt
669-129074.trans.txt
6818-68772.trans.txt
6818-76332.trans.txt
696-92939.trans.txt
696-93314.trans.txt
7059-77897.trans.txt
7059-77900.trans.txt
7059-88364.trans.txt
7078-271888.trans.txt
7113-86041.trans.txt
7148-59157.trans.txt
7148-7763.trans.txt
7148-82991.trans.txt
7178-34644.trans.txt
7178-34645.trans.txt
730-358.trans.txt
730-359.trans.txt
730-360.trans.txt
7302-86814.trans.txt
7302-86815.trans.txt
7511-102419.trans.txt
7511-102420.trans.txt
7517-100429.trans.txt
7517-100437.trans.txt
7517-100442.trans.txt
7635-105409.trans.txt
7635-105661.trans.txt
7780-274562.trans.txt
7794-295947.trans.txt
7794-295948.trans.txt
7794-295955.trans.txt
7800-283478.trans.txt
7800-283492.trans.txt
7800-283493.trans.txt
7859-102518.trans.txt
7859-102519.trans.txt
7859-102521.trans.txt
8014-112586.trans.txt
8014-112602.trans.txt
8014-280382.trans.txt
8051-118101.trans.txt
8051-119902.trans.txt
8051-295385.trans.txt
8123-275193.trans.txt
8123-275209.trans.txt
8123-275216.trans.txt
8238-274553.trans.txt
8238-283452.trans.txt
83-11691.trans.txt
83-3054.trans.txt
83-9960.trans.txt
8312-279790.trans.txt
8312-279791.trans.txt
8324-286681.trans.txt
8324-286682.trans.txt
8324-286683.trans.txt
8465-246940.trans.txt
8465-246942.trans.txt
8465-246943.trans.txt
8465-246947.trans.txt
8468-286673.trans.txt
8468-294887.trans.txt
8468-295198.trans.txt
87-121553.trans.txt
887-123289.trans.txt
887-123290.trans.txt
887-123291.trans.txt
89-218.trans.txt
89-219.trans.txt
8975-270782.trans.txt

In [11]:
#Directory that contain all the train audio files
os.mkdir("voice")

In [12]:
#copying all files in a single directory named "voice"
for i in os.listdir("male"):
    shutil.copy("male/"+i,"voice/")

In [13]:
for i in os.listdir("female"):
    shutil.copy("female/"+i,"voice/")

### For Test Data

In [17]:
df=pd.read_csv("LibriSpeechTest/SPEAKERS_MODIFIED.txt",sep="|")

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2484 entries, 0 to 2483
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  2484 non-null   int64
 1   SEX                 2484 non-null   object
 2    SUBSET             2484 non-null   object
 3   MINUTES             2484 non-null   float64
 4    NAME               2484 non-null   object
dtypes: float64(1), int64(1), object(3)
memory usage: 97.2+ KB

In [19]:
df.columns

Index(['ID  ', 'SEX', ' SUBSET           ', 'MINUTES', ' NAME'], dtype='object')

In [20]:
#Stripping spaces from the columns name
df.columns=[i.strip() for i in df.columns]
df.columns

Index(['ID', 'SEX', 'SUBSET', 'MINUTES', 'NAME'], dtype='object')

In [21]:
#Striping spaces from the data values except columns that caontain int and float values
for i in df.columns[1:3]:
    df[i]=df[i].apply(lambda x:x.strip())
for i in df.columns[4:]:
    df[i]=df[i].apply(lambda x:x.strip())

In [22]:
df['SUBSET'].value_counts().axes[0]

Index(['train-other-500', 'train-clean-360', 'train-clean-100', 'test-clean',
       'dev-clean', 'test-other', 'dev-other'],
      dtype='object')

In [23]:
df=df[df['SUBSET']=="test-clean"]

In [24]:
df.shape

(40, 5)

In [25]:
df.head()

      ID SEX      SUBSET  MINUTES                  NAME
33    61   M  test-clean     8.08   Paul-Gabriel Wiener
70   121   F  test-clean     8.01        Nikolle Doolin
125  237   F  test-clean     8.02           rachelellen
141  260   M  test-clean     8.05             Brad Bush
286  672   M  test-clean     8.27  Taylor Burton-Edward

In [26]:
df.drop(["SUBSET","MINUTES","NAME"],inplace=True,axis=1)

In [27]:
df.reset_index(drop=True)

      ID SEX
0     61   M
1    121   F
2    237   F
3    260   M
4    672   M
5    908   M
6   1089   M
7   1188   M
8   1221   F
9   1284   F
10  1320   M
11  1580   F
12  1995   F
13  2094   F
14  2300   M
15  2830   M
16  2961   F
17  3570   F
18  3575   F
19  3729   F
20  4077   M
21  4446   F
22  4507   F
23  4970   F
24  4992   F
25  5105   M
26  5142   F
27  5639   M
28  5683   F
29  6829   F
30  6930   M
31  7021   M
32  7127   M
33  7176   M
34  7729   M
35  8224   M
36  8230   M
37  8455   M
38  8463   F
39  8555   F

In [28]:
file_path="LibriSpeechTrain/train-clean-100"

In [29]:
os.mkdir("test_male")
os.mkdir("test_female")

In [30]:
def make_folders(files):
    
    z=0
    if files.SEX=="M":
        z=1
    print(files.ID,files.SEX,z)
    
    # Sets the name to be the path to where the file is in my computer
    file_name = os.path.join(os.path.abspath("LibriSpeechTest/test-clean"+'/'+str(files.ID)))
    dir_list=os.listdir(file_name)
    if z==1:
        for i in dir_list:
            for j in os.listdir(file_name+"/"+i):
                #shutil.copy(src,dest)
                shutil.copy(file_name+"/"+i+"/"+j,"test_male/")
    else:
        for i in dir_list:
            for j in os.listdir(file_name+"/"+i):
                #shutil.copy(src,dest)
                shutil.copy(file_name+"/"+i+"/"+j,"test_female/")

In [31]:
df.apply(make_folders,axis=1)

61 M 1
121 F 0
237 F 0
260 M 1
672 M 1
908 M 1
1089 M 1
1188 M 1
1221 F 0
1284 F 0
1320 M 1
1580 F 0
1995 F 0
2094 F 0
2300 M 1
2830 M 1
2961 F 0
3570 F 0
3575 F 0
3729 F 0
4077 M 1
4446 F 0
4507 F 0
4970 F 0
4992 F 0
5105 M 1
5142 F 0
5639 M 1
5683 F 0
6829 F 0
6930 M 1
7021 M 1
7127 M 1
7176 M 1
7729 M 1
8224 M 1
8230 M 1
8455 M 1
8463 F 0
8555 F 0

33      None
70      None
125     None
141     None
286     None
358     None
415     None
444     None
448     None
474     None
483     None
563     None
704     None
740     None
796     None
919     None
941     None
1101    None
1103    None
1139    None
1234    None
1333    None
1345    None
1447    None
1451    None
1482    None
1492    None
1598    None
1612    None
1932    None
1958    None
1983    None
2012    None
2028    None
2185    None
2326    None
2330    None
2389    None
2392    None
2414    None
dtype: object

In [32]:
#Removinf unnecessary text files from male and female directory
for i in os.listdir('test_male/'):
    if i[-3:]=='txt':
        os.remove("test_male/"+i)
        print(i)
for i in os.listdir('test_female/'):
    if i[-3:]=='txt':
        os.remove("test_female/"+i)
        print(i)

1089-134686.trans.txt
1089-134691.trans.txt
1188-133604.trans.txt
1320-122612.trans.txt
1320-122617.trans.txt
2300-131720.trans.txt
260-123286.trans.txt
260-123288.trans.txt
260-123440.trans.txt
2830-3979.trans.txt
2830-3980.trans.txt
4077-13751.trans.txt
4077-13754.trans.txt
5105-28233.trans.txt
5105-28240.trans.txt
5105-28241.trans.txt
5639-40744.trans.txt
61-70968.trans.txt
61-70970.trans.txt
672-122797.trans.txt
6930-75918.trans.txt
6930-76324.trans.txt
6930-81414.trans.txt
7021-79730.trans.txt
7021-79740.trans.txt
7021-79759.trans.txt
7021-85628.trans.txt
7127-75946.trans.txt
7127-75947.trans.txt
7176-88083.trans.txt
7176-92135.trans.txt
7729-102255.trans.txt
8224-274381.trans.txt
8224-274384.trans.txt
8230-279154.trans.txt
8455-210777.trans.txt
908-157963.trans.txt
908-31957.trans.txt
121-121726.trans.txt
121-123852.trans.txt
121-123859.trans.txt
121-127105.trans.txt
1221-135766.trans.txt
1221-135767.trans.txt
1284-1180.trans.txt
1284-1181.trans.txt
1284-134647.trans.txt
1580-141083.trans.txt
1580-141084.trans.txt
1995-1826.trans.txt
1995-1836.trans.txt
1995-1837.trans.txt
2094-142345.trans.txt
237-126133.trans.txt
237-134493.trans.txt
237-134500.trans.txt
2961-960.trans.txt
2961-961.trans.txt
3570-5694.trans.txt
3570-5695.trans.txt
3570-5696.trans.txt
3575-170457.trans.txt
3729-6852.trans.txt
4446-2271.trans.txt
4446-2273.trans.txt
4446-2275.trans.txt
4507-16021.trans.txt
4970-29093.trans.txt
4970-29095.trans.txt
4992-23283.trans.txt
4992-41797.trans.txt
4992-41806.trans.txt
5142-33396.trans.txt
5142-36377.trans.txt
5142-36586.trans.txt
5142-36600.trans.txt
5683-32865.trans.txt
5683-32866.trans.txt
5683-32879.trans.txt
6829-68769.trans.txt
6829-68771.trans.txt
8463-287645.trans.txt
8463-294825.trans.txt
8463-294828.trans.txt
8555-284447.trans.txt
8555-284449.trans.txt
8555-292519.trans.txt

In [35]:
#Directory that contain all the test audio files
os.mkdir("new_test_male_female")

In [36]:
#copying all test files in a single directory named "new_test_male_female" siillar to "voice" for train data
for i in os.listdir("test_male"):
    shutil.copy("test_male/"+i,"new_test_male_female/")

In [37]:
for i in os.listdir("test_female"):
    shutil.copy("test_female/"+i,"new_test_male_female/")